name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - sssapi-api-build-success
      - sssapi-api-build-warning
      # - sssapi-api-build-failure

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup Package
        run: npm i

      - name: Build
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
